# Generated by Django 3.2.3 on 2021-06-07 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancopreguntas.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('opcion1', models.CharField(max_length=80)),
                ('opcion2', models.CharField(max_length=80)),
                ('opcion3', models.CharField(max_length=80)),
                ('opcionRespuesta', models.CharField(max_length=80)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancopreguntas.modulo')),
            ],
        ),
    ]
