# Generated by Django 3.2.3 on 2021-06-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='correcta',
            field=models.BooleanField(default=False),
        ),
    ]
