# Generated by Django 3.2.3 on 2021-06-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_respuesta_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='porcentaje',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
