# Generated by Django 3.2.3 on 2021-06-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuario.user')),
                ('programa_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.programaacademico')),
            ],
        ),
    ]
