# Generated by Django 3.2.3 on 2021-06-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_administrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='programa_academico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.programaacademico'),
        ),
    ]
